//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReglasNegocio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReglasNegocio() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGS.SGV.Strings.ReglasNegocio", typeof(ReglasNegocio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Fechas consignadas: {0} - {1}.
        /// </summary>
        public static string AprobacionComentarioSolicitudConsignada {
            get {
                return ResourceManager.GetString("AprobacionComentarioSolicitudConsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabando Particion Final de la Solicitud: {0} - {1}.
        /// </summary>
        public static string AprobacionComentarioSolicitudFinal {
            get {
                return ResourceManager.GetString("AprobacionComentarioSolicitudFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabando una parte de la Solicitud: {0} - {1}.
        /// </summary>
        public static string AprobacionComentarioSolicitudParte {
            get {
                return ResourceManager.GetString("AprobacionComentarioSolicitudParte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Regularización Fechas consignadas: {0} - {1}.
        /// </summary>
        public static string AprobacionRegularizacionFechasConsignadas {
            get {
                return ResourceManager.GetString("AprobacionRegularizacionFechasConsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabando Particion Final de la Solicitud de Regularización : {0} - {1}.
        /// </summary>
        public static string AprobacionRegularizacionGrabaParticionFinal {
            get {
                return ResourceManager.GetString("AprobacionRegularizacionGrabaParticionFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Individual aprobada fuera de fecha, se le considera el pago a la próxima nómina. Grabando Particion Final de la Solicitud de Regularización : {0} - {1}.
        /// </summary>
        public static string AprobacionRegularizacionGrabaParticionFinalFueraFecha {
            get {
                return ResourceManager.GetString("AprobacionRegularizacionGrabaParticionFinalFueraFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabando una parte de la Solicitud de Regularización : {0} - {1}.
        /// </summary>
        public static string AprobacionRegularizacionGrabarParte {
            get {
                return ResourceManager.GetString("AprobacionRegularizacionGrabarParte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Individual aprobada fuera de fecha, se le considera el pago a la próxima nómina. Grabando una parte de la Solicitud : {0} - {1}.
        /// </summary>
        public static string AprobacionRegularizacionGrabarParteFueraFecha {
            get {
                return ResourceManager.GetString("AprobacionRegularizacionGrabarParteFueraFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Individual aprobada fuera de fecha, se le considera el pago a la próxima nómina. Fechas consignadas: {0} - {1}.
        /// </summary>
        public static string AprobacionRegularizacionIndividualFueraFecha {
            get {
                return ResourceManager.GetString("AprobacionRegularizacionIndividualFueraFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido aprobar la solicitud de Regularización para el Cip: {0}.
        /// </summary>
        public static string AprobacionRegularizacionNoAprobado {
            get {
                return ResourceManager.GetString("AprobacionRegularizacionNoAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las solicitudes fueron aprobadas correctamente..
        /// </summary>
        public static string AprobacionSolicitudes {
            get {
                return ResourceManager.GetString("AprobacionSolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las solicitudes fueron aprobadas correctamente. Se ha enviado un correo a los Trabajadores informándoles de la acción..
        /// </summary>
        public static string AprobacionSolicitudesEnvioMail {
            get {
                return ResourceManager.GetString("AprobacionSolicitudesEnvioMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las solicitudes fueron aprobadas correctamente. Algunos de los correos no se pudieron enviar correctamente a los Trabajadores informándoles de la acción..
        /// </summary>
        public static string AprobacionSolicitudesEnvioMailIncompleto {
            get {
                return ResourceManager.GetString("AprobacionSolicitudesEnvioMailIncompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error y no se pudo aprobar la solicitud I. Por favor vuelva a intentarlo.  {0}.
        /// </summary>
        public static string AprobacionSolicitudesErrorI {
            get {
                return ResourceManager.GetString("AprobacionSolicitudesErrorI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error y no se pudo aprobar la solicitud S. Por favor vuelva a intentarlo. {0}.
        /// </summary>
        public static string AprobacionSolicitudesErrorS {
            get {
                return ResourceManager.GetString("AprobacionSolicitudesErrorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un cruce de licencia en las fechas de la solicitud para el Cip: {0}..
        /// </summary>
        public static string AprobacionValidaCruceLicenciaFechas {
            get {
                return ResourceManager.GetString("AprobacionValidaCruceLicenciaFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un cruce con un registro en goce ya programado para el Cip: {0}..
        /// </summary>
        public static string AprobacionValidaCruceProgramado {
            get {
                return ResourceManager.GetString("AprobacionValidaCruceProgramado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un cruce con una solicitud ya aprobado para el Cip: {0}..
        /// </summary>
        public static string AprobacionValidaCruceSolicitudAprobada {
            get {
                return ResourceManager.GetString("AprobacionValidaCruceSolicitudAprobada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede aprobar la solicitud del Cip {0} debido a que no hay dias disponibles..
        /// </summary>
        public static string AprobacionValidaDiasDisponibles {
            get {
                return ResourceManager.GetString("AprobacionValidaDiasDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de días de la solicitud es mayor al disponible del Cip: {0}..
        /// </summary>
        public static string AprobacionValidaDiasMayorDisponible {
            get {
                return ResourceManager.GetString("AprobacionValidaDiasMayorDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de días de la solicitud es mayor al disponible de pago del Cip: {0}..
        /// </summary>
        public static string AprobacionValidaDiasMayorDisponiblePago {
            get {
                return ResourceManager.GetString("AprobacionValidaDiasMayorDisponiblePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede aprobar la solicitud del Cip {0} debido a que ya pasó la fecha de corte para la aprobación..
        /// </summary>
        public static string AprobacionValidaFechaCorte {
            get {
                return ResourceManager.GetString("AprobacionValidaFechaCorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede Aprobar, su fecha fin deberá ser {0} debido a que la finalización de las vacaciones no debe coincidir con el inicio de días festivos o fin de semana..
        /// </summary>
        public static string AprobacionValidaFechaFin {
            get {
                return ResourceManager.GetString("AprobacionValidaFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede Aprobar, su fecha fin deberá ser {0} debido a que tiene un registro vacacional continuado..
        /// </summary>
        public static string AprobacionValidaFechaFinRegistroContinuo {
            get {
                return ResourceManager.GetString("AprobacionValidaFechaFinRegistroContinuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede Aprobar, su fecha inicio deberá ser {0} debido a que registró un combo vacacional previamente..
        /// </summary>
        public static string AprobacionValidaFechaInicio {
            get {
                return ResourceManager.GetString("AprobacionValidaFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un error en la generación del goce para el Cip: {0}..
        /// </summary>
        public static string AprobacionValidaGeneracionGoce {
            get {
                return ResourceManager.GetString("AprobacionValidaGeneracionGoce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un error al momento de trasladar una Regularizacion al mes próximo para el Cip: {0}..
        /// </summary>
        public static string AprobacionValidaTrasladoRegularizacion {
            get {
                return ResourceManager.GetString("AprobacionValidaTrasladoRegularizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su fecha inicio será {0} debido a que registró un combo vacacional previamente..
        /// </summary>
        public static string ComboVacacionalPrevio {
            get {
                return ResourceManager.GetString("ComboVacacionalPrevio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las fechas seleccionadas coinciden con un Combo Vacacional que lo beneficiará. Por esta razón, no puede tener a la fecha Vacaciones Vencidas..
        /// </summary>
        public static string ComboVacacionesVencidas {
            get {
                return ResourceManager.GetString("ComboVacacionesVencidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un cruce con un goce ya registrado para el intervalo de fechas: {0}.
        /// </summary>
        public static string CruceGoceRegistrado {
            get {
                return ResourceManager.GetString("CruceGoceRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un cruce con una licencia ya registrada para el intervalo de fechas: {0}.
        /// </summary>
        public static string CruceLicenciaRegistrada {
            get {
                return ResourceManager.GetString("CruceLicenciaRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe cruce con una solicitud individual con el intervalo ingresado para el Usuario: {0}.
        /// </summary>
        public static string CruceSolicitudIndividual {
            get {
                return ResourceManager.GetString("CruceSolicitudIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado un cruce con una solicitud ya registrado para el intervalo de fechas: {0}.
        /// </summary>
        public static string CruceSolicitudRegistrada {
            get {
                return ResourceManager.GetString("CruceSolicitudRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe cruce con una solicitud de regularización con el intervalo ingresado para el Usuario: {0}.
        /// </summary>
        public static string CruceSolicitudRegularizacion {
            get {
                return ResourceManager.GetString("CruceSolicitudRegularizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe cruce con una solicitud de reprogramación con el intervalo ingresado para el Usuario: {0}.
        /// </summary>
        public static string CruceSolicitudReprogramacion {
            get {
                return ResourceManager.GetString("CruceSolicitudReprogramacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su clave ha sido enviada.
        /// </summary>
        public static string CuentaEnviada {
            get {
                return ResourceManager.GetString("CuentaEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos ingresados no son validos.
        /// </summary>
        public static string DatosNoValidos {
            get {
                return ResourceManager.GetString("DatosNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su fecha fin será {0} debido a que la finalización de las vacaciones no debe coincidir con el inicio de días festivos o fin de semana..
        /// </summary>
        public static string DiasFestivosFindeSemana {
            get {
                return ResourceManager.GetString("DiasFestivosFindeSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los dias disponibles del Usuario: {0} es inferior a los solicitados.
        /// </summary>
        public static string DiasInferiorSolicitado {
            get {
                return ResourceManager.GetString("DiasInferiorSolicitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de días de la solicitud es mayor al disponible del Usuario: {0} al {1}.
        /// </summary>
        public static string DiasMayorDisponible {
            get {
                return ResourceManager.GetString("DiasMayorDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los días solicitados exceden de sus días disponibles. Sus días disponibles son: {0} al {1} ..
        /// </summary>
        public static string ExcenderDiasDisponibles {
            get {
                return ResourceManager.GetString("ExcenderDiasDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El goce será considerada como VACACIONES VENCIDAS debido a que excede al día máximo permitido, debe ingresar el goce con fechas anteriores..
        /// </summary>
        public static string GoceVacacionesVencidas {
            get {
                return ResourceManager.GetString("GoceVacacionesVencidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde que la fecha máxima para que el Mando apruebe la solicitud y sea considerada el pago en esa nómina es el {0} . Despues de esa fecha se considerará con una Reprogramación en la siguiente nómina.  ¿Desea grabar el registro?..
        /// </summary>
        public static string GrabarRegistroFechaMaxima {
            get {
                return ResourceManager.GetString("GrabarRegistroFechaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al Grabar. El usuario: {0} No presenta responsable asignado, por favor comuníquese con el administrador.  Su solicitud no fue registrada..
        /// </summary>
        public static string NoTieneAprobadorAsignado {
            get {
                return ResourceManager.GetString("NoTieneAprobadorAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario: {0} no puede registrar ninguna Solicitud de Vacaciones por que no tiene Rol activo. Consulte con el Mando Responsable y/o Administrador del Sistema..
        /// </summary>
        public static string NoTieneRol {
            get {
                return ResourceManager.GetString("NoTieneRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario: {0} no tiene rol activo..
        /// </summary>
        public static string NoTieneRolActivo {
            get {
                return ResourceManager.GetString("NoTieneRolActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su fecha fin será {0} debido a que registró un vacacional posteriormente..
        /// </summary>
        public static string RegistroVacacionalPosterior {
            get {
                return ResourceManager.GetString("RegistroVacacionalPosterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Le informamos que podrá solicitar el ìntegro de sus vacaciones correspondientes al período actual..
        /// </summary>
        public static string RespuestaVacaciones {
            get {
                return ResourceManager.GetString("RespuestaVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted tiene {0} días ganados, Ud. puede solicitar hasta {1} días, para ello ingrese una fecha de inicio mayor a {2} ..
        /// </summary>
        public static string SolicitarDiasTruncos {
            get {
                return ResourceManager.GetString("SolicitarDiasTruncos", resourceCulture);
            }
        }
    }
}
