//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Web.WsUnidadServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsUnidadServicio.IUnidadServicio")]
    public interface IUnidadServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadServicio/ListarCCRPerfil", ReplyAction="http://tempuri.org/IUnidadServicio/ListarCCRPerfilResponse")]
        System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto> ListarCCRPerfil(TGS.SGV.Modelo.Dto.UnidadDtoRequest unidadDtoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnidadServicio/ListarCCRPerfil", ReplyAction="http://tempuri.org/IUnidadServicio/ListarCCRPerfilResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto>> ListarCCRPerfilAsync(TGS.SGV.Modelo.Dto.UnidadDtoRequest unidadDtoRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnidadServicioChannel : TGS.SGV.Web.WsUnidadServicio.IUnidadServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnidadServicioClient : System.ServiceModel.ClientBase<TGS.SGV.Web.WsUnidadServicio.IUnidadServicio>, TGS.SGV.Web.WsUnidadServicio.IUnidadServicio {
        
        public UnidadServicioClient() {
        }
        
        public UnidadServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnidadServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnidadServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnidadServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto> ListarCCRPerfil(TGS.SGV.Modelo.Dto.UnidadDtoRequest unidadDtoRequest) {
            return base.Channel.ListarCCRPerfil(unidadDtoRequest);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto>> ListarCCRPerfilAsync(TGS.SGV.Modelo.Dto.UnidadDtoRequest unidadDtoRequest) {
            return base.Channel.ListarCCRPerfilAsync(unidadDtoRequest);
        }
    }
}
