//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Web.WsTrabajadorServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsTrabajadorServicio.ITrabajadorServicio")]
    public interface ITrabajadorServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrabajadorServicio/ObtenerDatosTrabajador", ReplyAction="http://tempuri.org/ITrabajadorServicio/ObtenerDatosTrabajadorResponse")]
        TGS.SGV.Modelo.Dto.TrabajadorResponse ObtenerDatosTrabajador(string CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrabajadorServicio/ObtenerDatosTrabajador", ReplyAction="http://tempuri.org/ITrabajadorServicio/ObtenerDatosTrabajadorResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.TrabajadorResponse> ObtenerDatosTrabajadorAsync(string CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrabajadorServicio/ListarTrabajadorPorMando", ReplyAction="http://tempuri.org/ITrabajadorServicio/ListarTrabajadorPorMandoResponse")]
        TGS.SGV.Modelo.Dto.ListaDto[] ListarTrabajadorPorMando(TGS.SGV.Modelo.Dto.TrabajadorRequest trabajadorRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrabajadorServicio/ListarTrabajadorPorMando", ReplyAction="http://tempuri.org/ITrabajadorServicio/ListarTrabajadorPorMandoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ListaDto[]> ListarTrabajadorPorMandoAsync(TGS.SGV.Modelo.Dto.TrabajadorRequest trabajadorRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrabajadorServicioChannel : TGS.SGV.Web.WsTrabajadorServicio.ITrabajadorServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrabajadorServicioClient : System.ServiceModel.ClientBase<TGS.SGV.Web.WsTrabajadorServicio.ITrabajadorServicio>, TGS.SGV.Web.WsTrabajadorServicio.ITrabajadorServicio {
        
        public TrabajadorServicioClient() {
        }
        
        public TrabajadorServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrabajadorServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajadorServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajadorServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TGS.SGV.Modelo.Dto.TrabajadorResponse ObtenerDatosTrabajador(string CodigoUsuario) {
            return base.Channel.ObtenerDatosTrabajador(CodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.TrabajadorResponse> ObtenerDatosTrabajadorAsync(string CodigoUsuario) {
            return base.Channel.ObtenerDatosTrabajadorAsync(CodigoUsuario);
        }
        
        public TGS.SGV.Modelo.Dto.ListaDto[] ListarTrabajadorPorMando(TGS.SGV.Modelo.Dto.TrabajadorRequest trabajadorRequest) {
            return base.Channel.ListarTrabajadorPorMando(trabajadorRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ListaDto[]> ListarTrabajadorPorMandoAsync(TGS.SGV.Modelo.Dto.TrabajadorRequest trabajadorRequest) {
            return base.Channel.ListarTrabajadorPorMandoAsync(trabajadorRequest);
        }
    }
}
