//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Web.WsSolicitudServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsSolicitudServicio.ISolicitudServicio")]
    public interface ISolicitudServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarSolicitudResponse")]
        TGS.SGV.Modelo.Dto.SolicitudResponse ListarSolicitud(TGS.SGV.Modelo.Dto.SolicitudRequest solicitudRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarSolicitudResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.SolicitudResponse> ListarSolicitudAsync(TGS.SGV.Modelo.Dto.SolicitudRequest solicitudRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ObtenerSolicitudPorCodigo", ReplyAction="http://tempuri.org/ISolicitudServicio/ObtenerSolicitudPorCodigoResponse")]
        TGS.SGV.Modelo.Dto.SolicitudResponse ObtenerSolicitudPorCodigo(string CodigoSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ObtenerSolicitudPorCodigo", ReplyAction="http://tempuri.org/ISolicitudServicio/ObtenerSolicitudPorCodigoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.SolicitudResponse> ObtenerSolicitudPorCodigoAsync(string CodigoSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ActualizaSolicitudTrabajador", ReplyAction="http://tempuri.org/ISolicitudServicio/ActualizaSolicitudTrabajadorResponse")]
        TGS.SGV.Modelo.Modelo.Solicitud ActualizaSolicitudTrabajador(string CodigoSolicitud, string CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ActualizaSolicitudTrabajador", ReplyAction="http://tempuri.org/ISolicitudServicio/ActualizaSolicitudTrabajadorResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Modelo.Solicitud> ActualizaSolicitudTrabajadorAsync(string CodigoSolicitud, string CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/RegistraSolicitudTrabajador", ReplyAction="http://tempuri.org/ISolicitudServicio/RegistraSolicitudTrabajadorResponse")]
        TGS.SGV.Modelo.Base.Resultado<TGS.SGV.Modelo.Modelo.Solicitud> RegistraSolicitudTrabajador(TGS.SGV.Modelo.Modelo.Solicitud solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/RegistraSolicitudTrabajador", ReplyAction="http://tempuri.org/ISolicitudServicio/RegistraSolicitudTrabajadorResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<TGS.SGV.Modelo.Modelo.Solicitud>> RegistraSolicitudTrabajadorAsync(TGS.SGV.Modelo.Modelo.Solicitud solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarComboFeriado", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarComboFeriadoResponse")]
        TGS.SGV.Modelo.Dto.ComboFeriadoResponse ListarComboFeriado(TGS.SGV.Modelo.Dto.ComboFeriadoRequest comboFeriadoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarComboFeriado", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarComboFeriadoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ComboFeriadoResponse> ListarComboFeriadoAsync(TGS.SGV.Modelo.Dto.ComboFeriadoRequest comboFeriadoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ObtenerFechaDerecho", ReplyAction="http://tempuri.org/ISolicitudServicio/ObtenerFechaDerechoResponse")]
        TGS.SGV.Modelo.Dto.FechaDerechoResponse ObtenerFechaDerecho(TGS.SGV.Modelo.Dto.FechaDerechoRequest fechaDerechoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ObtenerFechaDerecho", ReplyAction="http://tempuri.org/ISolicitudServicio/ObtenerFechaDerechoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.FechaDerechoResponse> ObtenerFechaDerechoAsync(TGS.SGV.Modelo.Dto.FechaDerechoRequest fechaDerechoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitudResponse")]
        TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ListarEvaluacionSolicitud(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitudResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ListarEvaluacionSolicitudAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitudDPZ", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitudDPZResponse")]
        TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ListarEvaluacionSolicitudDPZ(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitudDPZ", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarEvaluacionSolicitudDPZResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ListarEvaluacionSolicitudDPZAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ProcesoAprobarEvaluacionSolicitudFutura", ReplyAction="http://tempuri.org/ISolicitudServicio/ProcesoAprobarEvaluacionSolicitudFuturaResp" +
            "onse")]
        TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ProcesoAprobarEvaluacionSolicitudFutura(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ProcesoAprobarEvaluacionSolicitudFutura", ReplyAction="http://tempuri.org/ISolicitudServicio/ProcesoAprobarEvaluacionSolicitudFuturaResp" +
            "onse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ProcesoAprobarEvaluacionSolicitudFuturaAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ProcesoModificarEvaluacionSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ProcesoModificarEvaluacionSolicitudResponse" +
            "")]
        TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ProcesoModificarEvaluacionSolicitud(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ProcesoModificarEvaluacionSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ProcesoModificarEvaluacionSolicitudResponse" +
            "")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ProcesoModificarEvaluacionSolicitudAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ProcesoRechazarEvaluacionSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ProcesoRechazarEvaluacionSolicitudResponse")]
        TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ProcesoRechazarEvaluacionSolicitud(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ProcesoRechazarEvaluacionSolicitud", ReplyAction="http://tempuri.org/ISolicitudServicio/ProcesoRechazarEvaluacionSolicitudResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ProcesoRechazarEvaluacionSolicitudAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitudServicioChannel : TGS.SGV.Web.WsSolicitudServicio.ISolicitudServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudServicioClient : System.ServiceModel.ClientBase<TGS.SGV.Web.WsSolicitudServicio.ISolicitudServicio>, TGS.SGV.Web.WsSolicitudServicio.ISolicitudServicio {
        
        public SolicitudServicioClient() {
        }
        
        public SolicitudServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TGS.SGV.Modelo.Dto.SolicitudResponse ListarSolicitud(TGS.SGV.Modelo.Dto.SolicitudRequest solicitudRequest) {
            return base.Channel.ListarSolicitud(solicitudRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.SolicitudResponse> ListarSolicitudAsync(TGS.SGV.Modelo.Dto.SolicitudRequest solicitudRequest) {
            return base.Channel.ListarSolicitudAsync(solicitudRequest);
        }
        
        public TGS.SGV.Modelo.Dto.SolicitudResponse ObtenerSolicitudPorCodigo(string CodigoSolicitud) {
            return base.Channel.ObtenerSolicitudPorCodigo(CodigoSolicitud);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.SolicitudResponse> ObtenerSolicitudPorCodigoAsync(string CodigoSolicitud) {
            return base.Channel.ObtenerSolicitudPorCodigoAsync(CodigoSolicitud);
        }
        
        public TGS.SGV.Modelo.Modelo.Solicitud ActualizaSolicitudTrabajador(string CodigoSolicitud, string CodigoUsuario) {
            return base.Channel.ActualizaSolicitudTrabajador(CodigoSolicitud, CodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Modelo.Solicitud> ActualizaSolicitudTrabajadorAsync(string CodigoSolicitud, string CodigoUsuario) {
            return base.Channel.ActualizaSolicitudTrabajadorAsync(CodigoSolicitud, CodigoUsuario);
        }
        
        public TGS.SGV.Modelo.Base.Resultado<TGS.SGV.Modelo.Modelo.Solicitud> RegistraSolicitudTrabajador(TGS.SGV.Modelo.Modelo.Solicitud solicitud) {
            return base.Channel.RegistraSolicitudTrabajador(solicitud);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<TGS.SGV.Modelo.Modelo.Solicitud>> RegistraSolicitudTrabajadorAsync(TGS.SGV.Modelo.Modelo.Solicitud solicitud) {
            return base.Channel.RegistraSolicitudTrabajadorAsync(solicitud);
        }
        
        public TGS.SGV.Modelo.Dto.ComboFeriadoResponse ListarComboFeriado(TGS.SGV.Modelo.Dto.ComboFeriadoRequest comboFeriadoRequest) {
            return base.Channel.ListarComboFeriado(comboFeriadoRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ComboFeriadoResponse> ListarComboFeriadoAsync(TGS.SGV.Modelo.Dto.ComboFeriadoRequest comboFeriadoRequest) {
            return base.Channel.ListarComboFeriadoAsync(comboFeriadoRequest);
        }
        
        public TGS.SGV.Modelo.Dto.FechaDerechoResponse ObtenerFechaDerecho(TGS.SGV.Modelo.Dto.FechaDerechoRequest fechaDerechoRequest) {
            return base.Channel.ObtenerFechaDerecho(fechaDerechoRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.FechaDerechoResponse> ObtenerFechaDerechoAsync(TGS.SGV.Modelo.Dto.FechaDerechoRequest fechaDerechoRequest) {
            return base.Channel.ObtenerFechaDerechoAsync(fechaDerechoRequest);
        }
        
        public TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ListarEvaluacionSolicitud(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ListarEvaluacionSolicitud(ESRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ListarEvaluacionSolicitudAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ListarEvaluacionSolicitudAsync(ESRequest);
        }
        
        public TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ListarEvaluacionSolicitudDPZ(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ListarEvaluacionSolicitudDPZ(ESRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ListarEvaluacionSolicitudDPZAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ListarEvaluacionSolicitudDPZAsync(ESRequest);
        }
        
        public TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ProcesoAprobarEvaluacionSolicitudFutura(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ProcesoAprobarEvaluacionSolicitudFutura(ESRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ProcesoAprobarEvaluacionSolicitudFuturaAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ProcesoAprobarEvaluacionSolicitudFuturaAsync(ESRequest);
        }
        
        public TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ProcesoModificarEvaluacionSolicitud(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ProcesoModificarEvaluacionSolicitud(ESRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ProcesoModificarEvaluacionSolicitudAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ProcesoModificarEvaluacionSolicitudAsync(ESRequest);
        }
        
        public TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse ProcesoRechazarEvaluacionSolicitud(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ProcesoRechazarEvaluacionSolicitud(ESRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EvaluacionSolicitudResponse> ProcesoRechazarEvaluacionSolicitudAsync(TGS.SGV.Modelo.Dto.EvaluacionSolicitudRequest ESRequest) {
            return base.Channel.ProcesoRechazarEvaluacionSolicitudAsync(ESRequest);
        }
    }
}
