//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Web.WsUsuarioServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsUsuarioServicio.IUsuarioServicio")]
    public interface IUsuarioServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/ValidarIngreso", ReplyAction="http://tempuri.org/IUsuarioServicio/ValidarIngresoResponse")]
        TGS.SGV.Modelo.Base.Resultado<string> ValidarIngreso(string usuarioLogin, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/ValidarIngreso", ReplyAction="http://tempuri.org/IUsuarioServicio/ValidarIngresoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<string>> ValidarIngresoAsync(string usuarioLogin, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/CambiarCLave", ReplyAction="http://tempuri.org/IUsuarioServicio/CambiarCLaveResponse")]
        TGS.SGV.Modelo.Base.Resultado<string> CambiarCLave(string idUsuario, string claveAnterior, string claveNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/CambiarCLave", ReplyAction="http://tempuri.org/IUsuarioServicio/CambiarCLaveResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<string>> CambiarCLaveAsync(string idUsuario, string claveAnterior, string claveNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/EnvioClaveUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/EnvioClaveUsuarioResponse")]
        TGS.SGV.Modelo.Base.Resultado<string> EnvioClaveUsuario(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/EnvioClaveUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/EnvioClaveUsuarioResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<string>> EnvioClaveUsuarioAsync(string nroDocumento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServicioChannel : TGS.SGV.Web.WsUsuarioServicio.IUsuarioServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServicioClient : System.ServiceModel.ClientBase<TGS.SGV.Web.WsUsuarioServicio.IUsuarioServicio>, TGS.SGV.Web.WsUsuarioServicio.IUsuarioServicio {
        
        public UsuarioServicioClient() {
        }
        
        public UsuarioServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TGS.SGV.Modelo.Base.Resultado<string> ValidarIngreso(string usuarioLogin, string claveUsuario) {
            return base.Channel.ValidarIngreso(usuarioLogin, claveUsuario);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<string>> ValidarIngresoAsync(string usuarioLogin, string claveUsuario) {
            return base.Channel.ValidarIngresoAsync(usuarioLogin, claveUsuario);
        }
        
        public TGS.SGV.Modelo.Base.Resultado<string> CambiarCLave(string idUsuario, string claveAnterior, string claveNueva) {
            return base.Channel.CambiarCLave(idUsuario, claveAnterior, claveNueva);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<string>> CambiarCLaveAsync(string idUsuario, string claveAnterior, string claveNueva) {
            return base.Channel.CambiarCLaveAsync(idUsuario, claveAnterior, claveNueva);
        }
        
        public TGS.SGV.Modelo.Base.Resultado<string> EnvioClaveUsuario(string nroDocumento) {
            return base.Channel.EnvioClaveUsuario(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Base.Resultado<string>> EnvioClaveUsuarioAsync(string nroDocumento) {
            return base.Channel.EnvioClaveUsuarioAsync(nroDocumento);
        }
    }
}
