//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Web.WsEmpresaServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsEmpresaServicio.IEmpresaServicio")]
    public interface IEmpresaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaServicio/ListarEmpresa", ReplyAction="http://tempuri.org/IEmpresaServicio/ListarEmpresaResponse")]
        System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto> ListarEmpresa(TGS.SGV.Modelo.Dto.EmpresaRequest empresaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaServicio/ListarEmpresa", ReplyAction="http://tempuri.org/IEmpresaServicio/ListarEmpresaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto>> ListarEmpresaAsync(TGS.SGV.Modelo.Dto.EmpresaRequest empresaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteCip", ReplyAction="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteCipResponse")]
        TGS.SGV.Modelo.Dto.EmpresaResponse ObtenerFechaCorteCip(string CodigoEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteCip", ReplyAction="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteCipResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EmpresaResponse> ObtenerFechaCorteCipAsync(string CodigoEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteEvaluacion", ReplyAction="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteEvaluacionResponse")]
        TGS.SGV.Modelo.Dto.EmpresaResponse ObtenerFechaCorteEvaluacion(string CodigoEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteEvaluacion", ReplyAction="http://tempuri.org/IEmpresaServicio/ObtenerFechaCorteEvaluacionResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EmpresaResponse> ObtenerFechaCorteEvaluacionAsync(string CodigoEmpleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresaServicioChannel : TGS.SGV.Web.WsEmpresaServicio.IEmpresaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaServicioClient : System.ServiceModel.ClientBase<TGS.SGV.Web.WsEmpresaServicio.IEmpresaServicio>, TGS.SGV.Web.WsEmpresaServicio.IEmpresaServicio {
        
        public EmpresaServicioClient() {
        }
        
        public EmpresaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto> ListarEmpresa(TGS.SGV.Modelo.Dto.EmpresaRequest empresaRequest) {
            return base.Channel.ListarEmpresa(empresaRequest);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TGS.SGV.Modelo.Dto.ListaDto>> ListarEmpresaAsync(TGS.SGV.Modelo.Dto.EmpresaRequest empresaRequest) {
            return base.Channel.ListarEmpresaAsync(empresaRequest);
        }
        
        public TGS.SGV.Modelo.Dto.EmpresaResponse ObtenerFechaCorteCip(string CodigoEmpleado) {
            return base.Channel.ObtenerFechaCorteCip(CodigoEmpleado);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EmpresaResponse> ObtenerFechaCorteCipAsync(string CodigoEmpleado) {
            return base.Channel.ObtenerFechaCorteCipAsync(CodigoEmpleado);
        }
        
        public TGS.SGV.Modelo.Dto.EmpresaResponse ObtenerFechaCorteEvaluacion(string CodigoEmpleado) {
            return base.Channel.ObtenerFechaCorteEvaluacion(CodigoEmpleado);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.EmpresaResponse> ObtenerFechaCorteEvaluacionAsync(string CodigoEmpleado) {
            return base.Channel.ObtenerFechaCorteEvaluacionAsync(CodigoEmpleado);
        }
    }
}
