//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Web.WsParametroServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsParametroServicio.IParametroServicio")]
    public interface IParametroServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerParametroInterno", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerParametroInternoResponse")]
        TGS.SGV.Modelo.Dto.ParametroResponse ObtenerParametroInterno(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerParametroInterno", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerParametroInternoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ParametroResponse> ObtenerParametroInternoAsync(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerParametro", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerParametroResponse")]
        TGS.SGV.Modelo.Dto.ParametroResponse ObtenerParametro(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerParametro", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerParametroResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ParametroResponse> ObtenerParametroAsync(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerParametroAcceso", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerParametroAccesoResponse")]
        TGS.SGV.Modelo.Dto.ParametroAccesoResponse ObtenerParametroAcceso(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerParametroAcceso", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerParametroAccesoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ParametroAccesoResponse> ObtenerParametroAccesoAsync(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerIndicadoresFuturo", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerIndicadoresFuturoResponse")]
        TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse ObtenerIndicadoresFuturo(string codigoUsuario, string fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerIndicadoresFuturo", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerIndicadoresFuturoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse> ObtenerIndicadoresFuturoAsync(string codigoUsuario, string fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerGoceFuturo", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerGoceFuturoResponse")]
        TGS.SGV.Modelo.Dto.FechaGoceResponse ObtenerGoceFuturo(string CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerGoceFuturo", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerGoceFuturoResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.FechaGoceResponse> ObtenerGoceFuturoAsync(string CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerIndicadores", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerIndicadoresResponse")]
        TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse ObtenerIndicadores(string codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametroServicio/ObtenerIndicadores", ReplyAction="http://tempuri.org/IParametroServicio/ObtenerIndicadoresResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse> ObtenerIndicadoresAsync(string codigoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParametroServicioChannel : TGS.SGV.Web.WsParametroServicio.IParametroServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParametroServicioClient : System.ServiceModel.ClientBase<TGS.SGV.Web.WsParametroServicio.IParametroServicio>, TGS.SGV.Web.WsParametroServicio.IParametroServicio {
        
        public ParametroServicioClient() {
        }
        
        public ParametroServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParametroServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametroServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametroServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TGS.SGV.Modelo.Dto.ParametroResponse ObtenerParametroInterno(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest) {
            return base.Channel.ObtenerParametroInterno(parametroRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ParametroResponse> ObtenerParametroInternoAsync(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest) {
            return base.Channel.ObtenerParametroInternoAsync(parametroRequest);
        }
        
        public TGS.SGV.Modelo.Dto.ParametroResponse ObtenerParametro(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest) {
            return base.Channel.ObtenerParametro(parametroRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ParametroResponse> ObtenerParametroAsync(TGS.SGV.Modelo.Dto.ParametroRequest parametroRequest) {
            return base.Channel.ObtenerParametroAsync(parametroRequest);
        }
        
        public TGS.SGV.Modelo.Dto.ParametroAccesoResponse ObtenerParametroAcceso(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest) {
            return base.Channel.ObtenerParametroAcceso(usuarioRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ParametroAccesoResponse> ObtenerParametroAccesoAsync(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest) {
            return base.Channel.ObtenerParametroAccesoAsync(usuarioRequest);
        }
        
        public TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse ObtenerIndicadoresFuturo(string codigoUsuario, string fechaInicio) {
            return base.Channel.ObtenerIndicadoresFuturo(codigoUsuario, fechaInicio);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse> ObtenerIndicadoresFuturoAsync(string codigoUsuario, string fechaInicio) {
            return base.Channel.ObtenerIndicadoresFuturoAsync(codigoUsuario, fechaInicio);
        }
        
        public TGS.SGV.Modelo.Dto.FechaGoceResponse ObtenerGoceFuturo(string CodigoUsuario) {
            return base.Channel.ObtenerGoceFuturo(CodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.FechaGoceResponse> ObtenerGoceFuturoAsync(string CodigoUsuario) {
            return base.Channel.ObtenerGoceFuturoAsync(CodigoUsuario);
        }
        
        public TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse ObtenerIndicadores(string codigoUsuario) {
            return base.Channel.ObtenerIndicadores(codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.IndicadorTrabajadorResponse> ObtenerIndicadoresAsync(string codigoUsuario) {
            return base.Channel.ObtenerIndicadoresAsync(codigoUsuario);
        }
    }
}
