//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.SGV.Web.WsModuloSistemaServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsModuloSistemaServicio.IModuloSistemaServicio")]
    public interface IModuloSistemaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloSistemaServicio/ListarModuloUsuario", ReplyAction="http://tempuri.org/IModuloSistemaServicio/ListarModuloUsuarioResponse")]
        TGS.SGV.Modelo.Dto.ModuloSistemaResponse ListarModuloUsuario(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuloSistemaServicio/ListarModuloUsuario", ReplyAction="http://tempuri.org/IModuloSistemaServicio/ListarModuloUsuarioResponse")]
        System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ModuloSistemaResponse> ListarModuloUsuarioAsync(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuloSistemaServicioChannel : TGS.SGV.Web.WsModuloSistemaServicio.IModuloSistemaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuloSistemaServicioClient : System.ServiceModel.ClientBase<TGS.SGV.Web.WsModuloSistemaServicio.IModuloSistemaServicio>, TGS.SGV.Web.WsModuloSistemaServicio.IModuloSistemaServicio {
        
        public ModuloSistemaServicioClient() {
        }
        
        public ModuloSistemaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuloSistemaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloSistemaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloSistemaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TGS.SGV.Modelo.Dto.ModuloSistemaResponse ListarModuloUsuario(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest) {
            return base.Channel.ListarModuloUsuario(usuarioRequest);
        }
        
        public System.Threading.Tasks.Task<TGS.SGV.Modelo.Dto.ModuloSistemaResponse> ListarModuloUsuarioAsync(TGS.SGV.Modelo.Dto.UsuarioRequest usuarioRequest) {
            return base.Channel.ListarModuloUsuarioAsync(usuarioRequest);
        }
    }
}
